#common config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  tracing:
    enabled: true
  metrics:
    export:
      simple:
        enabled: true
tracing:
  zipkin:
    enabled: true
    endpoint: http://localhost:9411/api/v2/spans  # Zipkin server URL
