#common config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  sleuth:
    sampler:
      probability: 1.0 # This ensures 100% of requests are traced
  zipkin:
    base-url: http://localhost:9411  # Zipkin server URL
    enabled: true
